version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nectar-postgres
    environment:
      POSTGRES_DB: nectardb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nectar-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: nectar-minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: dara
      MINIO_ROOT_PASSWORD: dara1234
      MINIO_SERVER_URL: "https://necta-storage.sobothty.tech"
      MINIO_BROWSER_REDIRECT_URL: "https://necta-storage-console.sobothty.tech"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - nectar-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  app:
    image: krysobothty/nectar-app:latest
    container_name: nectar-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nectardb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: dara
      MINIO_SECRET_KEY: dara1234
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - nectar-network
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

networks:
  nectar-network:
    driver: bridge